DROP TABLE ACCEPT_TYPE_TBL;

CREATE TABLE ACCEPT_TYPE_TBL
(
    CODE    NUMBER NOT NULL,
    ORDER_STATUS    VARCHAR2(30)
);

COMMENT ON COLUMN ACCEPT_TYPE_TBL.CODE IS '상태코드';

COMMENT ON COLUMN ACCEPT_TYPE_TBL.ORDER_STATUS IS '주문상태';

COMMENT ON TABLE ACCEPT_TYPE_TBL IS '주문상태';

CREATE UNIQUE INDEX 엔터티1_PK27 ON ACCEPT_TYPE_TBL
( CODE );

ALTER TABLE ACCEPT_TYPE_TBL
DROP PRIMARY KEY;

ALTER TABLE ACCEPT_TYPE_TBL
 ADD CONSTRAINT 엔터티1_PK27 PRIMARY KEY ( CODE )
 USING INDEX 엔터티1_PK27;

COMMENT ON COLUMN ACCEPT_TYPE_TBL.CODE IS '상태코드';

COMMENT ON COLUMN ACCEPT_TYPE_TBL.ORDER_STATUS IS '주문상태';

COMMENT ON TABLE ACCEPT_TYPE_TBL IS '주문상태';


DROP TABLE AUTH_TBL;

CREATE TABLE AUTH_TBL
(
    CODE    NUMBER NOT NULL,
    AUTH    VARCHAR2(20)
);

COMMENT ON COLUMN AUTH_TBL.CODE IS '권한코드';

COMMENT ON COLUMN AUTH_TBL.AUTH IS '권한타입';

COMMENT ON TABLE AUTH_TBL IS '권한';

CREATE UNIQUE INDEX 엔터티1_PK25 ON AUTH_TBL
( CODE );

ALTER TABLE AUTH_TBL
DROP PRIMARY KEY;

ALTER TABLE AUTH_TBL
 ADD CONSTRAINT 엔터티1_PK25 PRIMARY KEY ( CODE )
 USING INDEX 엔터티1_PK25;

COMMENT ON COLUMN AUTH_TBL.CODE IS '권한코드';

COMMENT ON COLUMN AUTH_TBL.AUTH IS '권한타입';

COMMENT ON TABLE AUTH_TBL IS '권한';


DROP TABLE BANER_TBL;

CREATE TABLE BANER_TBL
(
    BANER_CODE    NUMBER NOT NULL,
    BANER_NAME    VARCHAR2(100),
    BANER_IMG    VARCHAR2(200),
    STATUS    VARCHAR2(10),
    BANER_ORDER    NUMBER
);

COMMENT ON COLUMN BANER_TBL.BANER_CODE IS '배너코드';

COMMENT ON COLUMN BANER_TBL.BANER_NAME IS '배너명';

COMMENT ON COLUMN BANER_TBL.BANER_IMG IS '이미지';

COMMENT ON COLUMN BANER_TBL.STATUS IS '사용여부';

COMMENT ON COLUMN BANER_TBL.BANER_ORDER IS '순서';

COMMENT ON TABLE BANER_TBL IS '배너';

CREATE UNIQUE INDEX 엔터티1_PK19 ON BANER_TBL
( BANER_CODE );

ALTER TABLE BANER_TBL
DROP PRIMARY KEY;

ALTER TABLE BANER_TBL
 ADD CONSTRAINT 엔터티1_PK19 PRIMARY KEY ( BANER_CODE )
 USING INDEX 엔터티1_PK19;

COMMENT ON COLUMN BANER_TBL.BANER_CODE IS '배너코드';

COMMENT ON COLUMN BANER_TBL.BANER_NAME IS '배너명';

COMMENT ON COLUMN BANER_TBL.BANER_IMG IS '이미지';

COMMENT ON COLUMN BANER_TBL.STATUS IS '사용여부';

COMMENT ON COLUMN BANER_TBL.BANER_ORDER IS '순서';

COMMENT ON TABLE BANER_TBL IS '배너';


DROP TABLE BOARD_TBL;

CREATE TABLE BOARD_TBL
(
    BOARD_CODE    VARCHAR2(15) NOT NULL,
    TYPE    VARCHAR2(30)
);

COMMENT ON COLUMN BOARD_TBL.BOARD_CODE IS '게시판 코드';

COMMENT ON COLUMN BOARD_TBL.TYPE IS '게시판 종류';

COMMENT ON TABLE BOARD_TBL IS '게시판 코드';

CREATE UNIQUE INDEX 엔터티1_PK15 ON BOARD_TBL
( BOARD_CODE );

ALTER TABLE BOARD_TBL
DROP PRIMARY KEY;

ALTER TABLE BOARD_TBL
 ADD CONSTRAINT 엔터티1_PK15 PRIMARY KEY ( BOARD_CODE )
 USING INDEX 엔터티1_PK15;

COMMENT ON COLUMN BOARD_TBL.BOARD_CODE IS '게시판 코드';

COMMENT ON COLUMN BOARD_TBL.TYPE IS '게시판 종류';

COMMENT ON TABLE BOARD_TBL IS '게시판 코드';


DROP TABLE CART_TBL;

CREATE TABLE CART_TBL
(
    MEM_CODE    NUMBER NOT NULL,
    SD_CODE    NUMBER NOT NULL,
    AMOUNT    NUMBER,
    CART_CODE    NUMBER NOT NULL
);

COMMENT ON COLUMN CART_TBL.MEM_CODE IS '회원코드';

COMMENT ON COLUMN CART_TBL.SD_CODE IS '반찬코드';

COMMENT ON COLUMN CART_TBL.AMOUNT IS '수량';

COMMENT ON COLUMN CART_TBL.CART_CODE IS '장바구니 코드';

COMMENT ON TABLE CART_TBL IS '장바구니';

CREATE UNIQUE INDEX 엔터티1_PK9 ON CART_TBL
( CART_CODE );

ALTER TABLE CART_TBL
DROP PRIMARY KEY;

ALTER TABLE CART_TBL
 ADD CONSTRAINT 엔터티1_PK9 PRIMARY KEY ( CART_CODE )
 USING INDEX 엔터티1_PK9;

COMMENT ON COLUMN CART_TBL.MEM_CODE IS '회원코드';

COMMENT ON COLUMN CART_TBL.SD_CODE IS '반찬코드';

COMMENT ON COLUMN CART_TBL.AMOUNT IS '수량';

COMMENT ON COLUMN CART_TBL.CART_CODE IS '장바구니 코드';

COMMENT ON TABLE CART_TBL IS '장바구니';


DROP TABLE CEO_TBL;

CREATE TABLE CEO_TBL
(
    STORE_NO    VARCHAR2(20),
    CEO_NAME    VARCHAR2(20),
    MEM_CODE    NUMBER NOT NULL,
    ACCOUNT    VARCHAR2(30),
    START_DATE    DATE
);

COMMENT ON COLUMN CEO_TBL.STORE_NO IS '사업자번호';

COMMENT ON COLUMN CEO_TBL.CEO_NAME IS '대표자명';

COMMENT ON COLUMN CEO_TBL.MEM_CODE IS '사업자코드';

COMMENT ON COLUMN CEO_TBL.ACCOUNT IS '계좌번호';

COMMENT ON COLUMN CEO_TBL.START_DATE IS '시작날짜';

COMMENT ON TABLE CEO_TBL IS '사업자';

CREATE UNIQUE INDEX 엔터티1_PK2 ON CEO_TBL
( MEM_CODE );

ALTER TABLE CEO_TBL
DROP PRIMARY KEY;

ALTER TABLE CEO_TBL
 ADD CONSTRAINT 엔터티1_PK2 PRIMARY KEY ( MEM_CODE )
 USING INDEX 엔터티1_PK2;

COMMENT ON COLUMN CEO_TBL.STORE_NO IS '사업자번호';

COMMENT ON COLUMN CEO_TBL.CEO_NAME IS '대표자명';

COMMENT ON COLUMN CEO_TBL.MEM_CODE IS '사업자코드';

COMMENT ON COLUMN CEO_TBL.ACCOUNT IS '계좌번호';

COMMENT ON COLUMN CEO_TBL.START_DATE IS '시작날짜';

COMMENT ON TABLE CEO_TBL IS '사업자';


DROP TABLE COUPON_STORE_TBL;

CREATE TABLE COUPON_STORE_TBL
(
    MEM_CODE    NUMBER NOT NULL,
    CP_CODE    NUMBER NOT NULL
);

COMMENT ON COLUMN COUPON_STORE_TBL.MEM_CODE IS '사업자코드';

COMMENT ON COLUMN COUPON_STORE_TBL.CP_CODE IS '쿠폰번호';

COMMENT ON TABLE COUPON_STORE_TBL IS '쿠폰-사업자';

CREATE UNIQUE INDEX 엔터티1_PK4 ON COUPON_STORE_TBL
( MEM_CODE,CP_CODE );

ALTER TABLE COUPON_STORE_TBL
DROP PRIMARY KEY;

ALTER TABLE COUPON_STORE_TBL
 ADD CONSTRAINT 엔터티1_PK4 PRIMARY KEY ( MEM_CODE,CP_CODE )
 USING INDEX 엔터티1_PK4;

COMMENT ON COLUMN COUPON_STORE_TBL.MEM_CODE IS '사업자코드';

COMMENT ON COLUMN COUPON_STORE_TBL.CP_CODE IS '쿠폰번호';

COMMENT ON TABLE COUPON_STORE_TBL IS '쿠폰-사업자';


DROP TABLE COUPON_TBL;

CREATE TABLE COUPON_TBL
(
    CP_CODE    NUMBER NOT NULL,
    CP_NAME    VARCHAR2(60),
    START_DATE    DATE,
    DISCOUNT_RATE    NUMBER,
    END_DATE    DATE,
    DC_CONDITION    NUMBER
);

COMMENT ON COLUMN COUPON_TBL.CP_CODE IS '쿠폰번호';

COMMENT ON COLUMN COUPON_TBL.CP_NAME IS '쿠폰이름';

COMMENT ON COLUMN COUPON_TBL.START_DATE IS '발행일';

COMMENT ON COLUMN COUPON_TBL.DISCOUNT_RATE IS '할인금액';

COMMENT ON COLUMN COUPON_TBL.END_DATE IS '유효기간';

COMMENT ON COLUMN COUPON_TBL.DC_CONDITION IS '할인조건';

COMMENT ON TABLE COUPON_TBL IS '쿠폰';

CREATE UNIQUE INDEX 엔터티1_PK3 ON COUPON_TBL
( CP_CODE );

ALTER TABLE COUPON_TBL
DROP PRIMARY KEY;

ALTER TABLE COUPON_TBL
 ADD CONSTRAINT 엔터티1_PK3 PRIMARY KEY ( CP_CODE )
 USING INDEX 엔터티1_PK3;

COMMENT ON COLUMN COUPON_TBL.CP_CODE IS '쿠폰번호';

COMMENT ON COLUMN COUPON_TBL.CP_NAME IS '쿠폰이름';

COMMENT ON COLUMN COUPON_TBL.START_DATE IS '발행일';

COMMENT ON COLUMN COUPON_TBL.DISCOUNT_RATE IS '할인금액';

COMMENT ON COLUMN COUPON_TBL.END_DATE IS '유효기간';

COMMENT ON COLUMN COUPON_TBL.DC_CONDITION IS '할인조건';

COMMENT ON TABLE COUPON_TBL IS '쿠폰';


DROP TABLE CP_HISTORY_TBL;

CREATE TABLE CP_HISTORY_TBL
(
    CP_CODE    NUMBER NOT NULL,
    MEM_CODE    NUMBER NOT NULL,
    USE_STATUS    VARCHAR2(3) DEFAULT 'N'
);

COMMENT ON COLUMN CP_HISTORY_TBL.CP_CODE IS '쿠폰번호';

COMMENT ON COLUMN CP_HISTORY_TBL.MEM_CODE IS '회원코드';

COMMENT ON COLUMN CP_HISTORY_TBL.USE_STATUS IS '사용여부';

COMMENT ON TABLE CP_HISTORY_TBL IS '발행내역';

CREATE UNIQUE INDEX 엔터티1_PK5 ON CP_HISTORY_TBL
( CP_CODE,MEM_CODE );

ALTER TABLE CP_HISTORY_TBL
DROP PRIMARY KEY;

ALTER TABLE CP_HISTORY_TBL
 ADD CONSTRAINT 엔터티1_PK5 PRIMARY KEY ( CP_CODE,MEM_CODE )
 USING INDEX 엔터티1_PK5;

COMMENT ON COLUMN CP_HISTORY_TBL.CP_CODE IS '쿠폰번호';

COMMENT ON COLUMN CP_HISTORY_TBL.MEM_CODE IS '회원코드';

COMMENT ON COLUMN CP_HISTORY_TBL.USE_STATUS IS '사용여부';

COMMENT ON TABLE CP_HISTORY_TBL IS '발행내역';


DROP TABLE FILE_TBL;

CREATE TABLE FILE_TBL
(
    FILE_CODE    NUMBER NOT NULL,
    FILE_NAME    VARCHAR2(250),
    POST_NO    NUMBER NOT NULL
);

COMMENT ON COLUMN FILE_TBL.FILE_CODE IS '파일코드';

COMMENT ON COLUMN FILE_TBL.FILE_NAME IS '파일명';

COMMENT ON COLUMN FILE_TBL.POST_NO IS '게시글 번호';

COMMENT ON TABLE FILE_TBL IS '파일';

CREATE UNIQUE INDEX 엔터티1_PK16 ON FILE_TBL
( FILE_CODE );

ALTER TABLE FILE_TBL
DROP PRIMARY KEY;

ALTER TABLE FILE_TBL
 ADD CONSTRAINT 엔터티1_PK16 PRIMARY KEY ( FILE_CODE )
 USING INDEX 엔터티1_PK16;

COMMENT ON COLUMN FILE_TBL.FILE_CODE IS '파일코드';

COMMENT ON COLUMN FILE_TBL.FILE_NAME IS '파일명';

COMMENT ON COLUMN FILE_TBL.POST_NO IS '게시글 번호';

COMMENT ON TABLE FILE_TBL IS '파일';


DROP TABLE HOT_TBL;

CREATE TABLE HOT_TBL
(
    HOT_NO    NUMBER NOT NULL,
    HOT_TAG    VARCHAR2(30)
);

COMMENT ON COLUMN HOT_TBL.HOT_NO IS '키워드 번호';

COMMENT ON COLUMN HOT_TBL.HOT_TAG IS '키워드 내용';

COMMENT ON TABLE HOT_TBL IS '핫키워드';

CREATE UNIQUE INDEX 엔터티1_PK21 ON HOT_TBL
( HOT_NO );

ALTER TABLE HOT_TBL
DROP PRIMARY KEY;

ALTER TABLE HOT_TBL
 ADD CONSTRAINT 엔터티1_PK21 PRIMARY KEY ( HOT_NO )
 USING INDEX 엔터티1_PK21;

COMMENT ON COLUMN HOT_TBL.HOT_NO IS '키워드 번호';

COMMENT ON COLUMN HOT_TBL.HOT_TAG IS '키워드 내용';

COMMENT ON TABLE HOT_TBL IS '핫키워드';


DROP TABLE JJIM_TBL;

CREATE TABLE JJIM_TBL
(
    MEM_CODE    NUMBER NOT NULL,
    CEO_CODE    NUMBER NOT NULL
);

COMMENT ON COLUMN JJIM_TBL.MEM_CODE IS '회원코드';

COMMENT ON COLUMN JJIM_TBL.CEO_CODE IS '사업자코드';

COMMENT ON TABLE JJIM_TBL IS '찜한가게';

CREATE UNIQUE INDEX 엔터티1_PK11 ON JJIM_TBL
( MEM_CODE,CEO_CODE );

ALTER TABLE JJIM_TBL
DROP PRIMARY KEY;

ALTER TABLE JJIM_TBL
 ADD CONSTRAINT 엔터티1_PK11 PRIMARY KEY ( MEM_CODE,CEO_CODE )
 USING INDEX 엔터티1_PK11;

COMMENT ON COLUMN JJIM_TBL.MEM_CODE IS '회원코드';

COMMENT ON COLUMN JJIM_TBL.CEO_CODE IS '사업자코드';

COMMENT ON TABLE JJIM_TBL IS '찜한가게';


DROP TABLE LOCATION;

CREATE TABLE LOCATION
(
    LOCATION_CODE    VARCHAR2(10) NOT NULL,
    LOCATION_NAME    VARCHAR2(20)
);

COMMENT ON COLUMN LOCATION.LOCATION_CODE IS '지역코드';

COMMENT ON COLUMN LOCATION.LOCATION_NAME IS '지역명';

COMMENT ON TABLE LOCATION IS '지역코드';

CREATE UNIQUE INDEX 엔터티1_PK1 ON LOCATION
( LOCATION_CODE );

ALTER TABLE LOCATION
DROP PRIMARY KEY;

ALTER TABLE LOCATION
 ADD CONSTRAINT 엔터티1_PK1 PRIMARY KEY ( LOCATION_CODE )
 USING INDEX 엔터티1_PK1;

COMMENT ON COLUMN LOCATION.LOCATION_CODE IS '지역코드';

COMMENT ON COLUMN LOCATION.LOCATION_NAME IS '지역명';

COMMENT ON TABLE LOCATION IS '지역코드';


DROP TABLE MANAGER_TBL;

CREATE TABLE MANAGER_TBL
(
    MEM_CODE    NUMBER NOT NULL,
    LAST_LOGIN    DATE,
    CODE    NUMBER NOT NULL
);

COMMENT ON COLUMN MANAGER_TBL.MEM_CODE IS '회원코드';

COMMENT ON COLUMN MANAGER_TBL.LAST_LOGIN IS '최근 접속일';

COMMENT ON COLUMN MANAGER_TBL.CODE IS '권한코드';

COMMENT ON TABLE MANAGER_TBL IS '관리자';

CREATE UNIQUE INDEX 엔터티1_PK7 ON MANAGER_TBL
( MEM_CODE );

ALTER TABLE MANAGER_TBL
DROP PRIMARY KEY;

ALTER TABLE MANAGER_TBL
 ADD CONSTRAINT 엔터티1_PK7 PRIMARY KEY ( MEM_CODE )
 USING INDEX 엔터티1_PK7;

COMMENT ON COLUMN MANAGER_TBL.MEM_CODE IS '회원코드';

COMMENT ON COLUMN MANAGER_TBL.LAST_LOGIN IS '최근 접속일';

COMMENT ON COLUMN MANAGER_TBL.CODE IS '권한코드';

COMMENT ON TABLE MANAGER_TBL IS '관리자';


DROP TABLE MEMBER_TBL;

CREATE TABLE MEMBER_TBL
(
    MEM_CODE    NUMBER NOT NULL,
    EMAIL    VARCHAR2(50),
    MEM_PWD    VARCHAR2(150),
    ADDRESS    VARCHAR2(300),
    POST_CODE    VARCHAR2(20),
    D_ADDRESS    VARCHAR2(100),
    PHONE    VARCHAR2(50),
    MEM_TYPE    VARCHAR2(10),
    LOCATION_CODE    VARCHAR2(10) NOT NULL,
    NICKNAME    VARCHAR2(25),
    MEM_ID    VARCHAR2(30),
    ENROLL_DATE    DATE DEFAULT SYSDATE,
    IS_DELETED    VARCHAR2(3) DEFAULT 'N'
);

COMMENT ON COLUMN MEMBER_TBL.MEM_CODE IS '회원코드';

COMMENT ON COLUMN MEMBER_TBL.EMAIL IS '이메일';

COMMENT ON COLUMN MEMBER_TBL.MEM_PWD IS '비밀번호';

COMMENT ON COLUMN MEMBER_TBL.ADDRESS IS '주소';

COMMENT ON COLUMN MEMBER_TBL.POST_CODE IS '우편번호';

COMMENT ON COLUMN MEMBER_TBL.D_ADDRESS IS '상세주소';

COMMENT ON COLUMN MEMBER_TBL.PHONE IS '휴대폰';

COMMENT ON COLUMN MEMBER_TBL.MEM_TYPE IS '회원구분';

COMMENT ON COLUMN MEMBER_TBL.LOCATION_CODE IS '지역코드';

COMMENT ON COLUMN MEMBER_TBL.NICKNAME IS '닉네임';

COMMENT ON COLUMN MEMBER_TBL.MEM_ID IS '아이디';

COMMENT ON COLUMN MEMBER_TBL.ENROLL_DATE IS '가입일';

COMMENT ON COLUMN MEMBER_TBL.IS_DELETED IS '상태';

COMMENT ON TABLE MEMBER_TBL IS '회원';

CREATE UNIQUE INDEX 엔터티1_PK ON MEMBER_TBL
( MEM_CODE );

ALTER TABLE MEMBER_TBL
DROP PRIMARY KEY;

ALTER TABLE MEMBER_TBL
 ADD CONSTRAINT 엔터티1_PK PRIMARY KEY ( MEM_CODE )
 USING INDEX 엔터티1_PK;

COMMENT ON COLUMN MEMBER_TBL.MEM_CODE IS '회원코드';

COMMENT ON COLUMN MEMBER_TBL.EMAIL IS '이메일';

COMMENT ON COLUMN MEMBER_TBL.MEM_PWD IS '비밀번호';

COMMENT ON COLUMN MEMBER_TBL.ADDRESS IS '주소';

COMMENT ON COLUMN MEMBER_TBL.POST_CODE IS '우편번호';

COMMENT ON COLUMN MEMBER_TBL.D_ADDRESS IS '상세주소';

COMMENT ON COLUMN MEMBER_TBL.PHONE IS '휴대폰';

COMMENT ON COLUMN MEMBER_TBL.MEM_TYPE IS '회원구분';

COMMENT ON COLUMN MEMBER_TBL.LOCATION_CODE IS '지역코드';

COMMENT ON COLUMN MEMBER_TBL.NICKNAME IS '닉네임';

COMMENT ON COLUMN MEMBER_TBL.MEM_ID IS '아이디';

COMMENT ON COLUMN MEMBER_TBL.ENROLL_DATE IS '가입일';

COMMENT ON COLUMN MEMBER_TBL.IS_DELETED IS '상태';

COMMENT ON TABLE MEMBER_TBL IS '회원';


DROP TABLE MEMBERSHIP_TBL;

CREATE TABLE MEMBERSHIP_TBL
(
    MS_CODE    VARCHAR2(10) NOT NULL,
    MS_TYPE    VARCHAR2(30),
    MS_DATE    DATE,
    MS_PRICE    NUMBER
);

COMMENT ON COLUMN MEMBERSHIP_TBL.MS_CODE IS '멤버십 코드';

COMMENT ON COLUMN MEMBERSHIP_TBL.MS_TYPE IS '종류';

COMMENT ON COLUMN MEMBERSHIP_TBL.MS_DATE IS '기간';

COMMENT ON COLUMN MEMBERSHIP_TBL.MS_PRICE IS '가격';

COMMENT ON TABLE MEMBERSHIP_TBL IS '멤버십';

CREATE UNIQUE INDEX 엔터티1_PK13 ON MEMBERSHIP_TBL
( MS_CODE );

ALTER TABLE MEMBERSHIP_TBL
DROP PRIMARY KEY;

ALTER TABLE MEMBERSHIP_TBL
 ADD CONSTRAINT 엔터티1_PK13 PRIMARY KEY ( MS_CODE )
 USING INDEX 엔터티1_PK13;

COMMENT ON COLUMN MEMBERSHIP_TBL.MS_CODE IS '멤버십 코드';

COMMENT ON COLUMN MEMBERSHIP_TBL.MS_TYPE IS '종류';

COMMENT ON COLUMN MEMBERSHIP_TBL.MS_DATE IS '기간';

COMMENT ON COLUMN MEMBERSHIP_TBL.MS_PRICE IS '가격';

COMMENT ON TABLE MEMBERSHIP_TBL IS '멤버십';


DROP TABLE MS_STORE_TBL;

CREATE TABLE MS_STORE_TBL
(
    MEM_CODE    NUMBER NOT NULL,
    MS_CODE    VARCHAR2(10) NOT NULL
);

COMMENT ON COLUMN MS_STORE_TBL.MEM_CODE IS '사업자코드';

COMMENT ON COLUMN MS_STORE_TBL.MS_CODE IS '멤버십 코드';

COMMENT ON TABLE MS_STORE_TBL IS '멤버십 사업자';

CREATE UNIQUE INDEX 엔터티1_PK24 ON MS_STORE_TBL
( MEM_CODE,MS_CODE );

ALTER TABLE MS_STORE_TBL
DROP PRIMARY KEY;

ALTER TABLE MS_STORE_TBL
 ADD CONSTRAINT 엔터티1_PK24 PRIMARY KEY ( MEM_CODE,MS_CODE )
 USING INDEX 엔터티1_PK24;

COMMENT ON COLUMN MS_STORE_TBL.MEM_CODE IS '사업자코드';

COMMENT ON COLUMN MS_STORE_TBL.MS_CODE IS '멤버십 코드';

COMMENT ON TABLE MS_STORE_TBL IS '멤버십 사업자';


DROP TABLE ORDER_INFO_TBL;

CREATE TABLE ORDER_INFO_TBL
(
    SD_CODE    NUMBER NOT NULL,
    AMONT    NUMBER,
    ORDER_CODE    NUMBER NOT NULL,
    PRO_NO    NUMBER NOT NULL,
    ORDER_CANCLE_TIME    DATE,
    ORDER_COMPLETE_TIME    DATE,
    ORDER_ACCEPT_TIME    DATE,
    ORDER_RUQEUST_TIME    DATE
);

COMMENT ON COLUMN ORDER_INFO_TBL.SD_CODE IS '반찬코드';

COMMENT ON COLUMN ORDER_INFO_TBL.AMONT IS '수량';

COMMENT ON COLUMN ORDER_INFO_TBL.ORDER_CODE IS '주문코드';

COMMENT ON COLUMN ORDER_INFO_TBL.PRO_NO IS '주문상품번호';

COMMENT ON COLUMN ORDER_INFO_TBL.ORDER_CANCLE_TIME IS '주문취소시간';

COMMENT ON COLUMN ORDER_INFO_TBL.ORDER_COMPLETE_TIME IS '주문완료시간';

COMMENT ON COLUMN ORDER_INFO_TBL.ORDER_ACCEPT_TIME IS '주문접수시간';

COMMENT ON COLUMN ORDER_INFO_TBL.ORDER_RUQEUST_TIME IS '주문신청시간';

COMMENT ON TABLE ORDER_INFO_TBL IS '주문정보';

CREATE UNIQUE INDEX 엔터티1_PK23 ON ORDER_INFO_TBL
( PRO_NO );

ALTER TABLE ORDER_INFO_TBL
DROP PRIMARY KEY;

ALTER TABLE ORDER_INFO_TBL
 ADD CONSTRAINT 엔터티1_PK23 PRIMARY KEY ( PRO_NO )
 USING INDEX 엔터티1_PK23;

COMMENT ON COLUMN ORDER_INFO_TBL.SD_CODE IS '반찬코드';

COMMENT ON COLUMN ORDER_INFO_TBL.AMONT IS '수량';

COMMENT ON COLUMN ORDER_INFO_TBL.ORDER_CODE IS '주문코드';

COMMENT ON COLUMN ORDER_INFO_TBL.PRO_NO IS '주문상품번호';

COMMENT ON COLUMN ORDER_INFO_TBL.ORDER_CANCLE_TIME IS '주문취소시간';

COMMENT ON COLUMN ORDER_INFO_TBL.ORDER_COMPLETE_TIME IS '주문완료시간';

COMMENT ON COLUMN ORDER_INFO_TBL.ORDER_ACCEPT_TIME IS '주문접수시간';

COMMENT ON COLUMN ORDER_INFO_TBL.ORDER_RUQEUST_TIME IS '주문신청시간';

COMMENT ON TABLE ORDER_INFO_TBL IS '주문정보';


DROP TABLE ORDER_TBL;

CREATE TABLE ORDER_TBL
(
    MEM_CODE    NUMBER NOT NULL,
    TOTAL_PRICE    NUMBER,
    ORDER_CODE    NUMBER NOT NULL,
    ORDER_TYPE    VARCHAR2(10),
    TAKE_TIME    TIMESTAMP,
    ADDRESS    VARCHAR2(180),
    PHONE    VARCHAR2(20),
    STORE_NAME    VARCHAR2(30),
    CODE    NUMBER NOT NULL
);

COMMENT ON COLUMN ORDER_TBL.MEM_CODE IS '회원코드';

COMMENT ON COLUMN ORDER_TBL.TOTAL_PRICE IS '구매금액';

COMMENT ON COLUMN ORDER_TBL.ORDER_CODE IS '주문코드';

COMMENT ON COLUMN ORDER_TBL.ORDER_TYPE IS '주문유형';

COMMENT ON COLUMN ORDER_TBL.TAKE_TIME IS '수령시간';

COMMENT ON COLUMN ORDER_TBL.ADDRESS IS '배송지';

COMMENT ON COLUMN ORDER_TBL.PHONE IS '연락처';

COMMENT ON COLUMN ORDER_TBL.STORE_NAME IS '주문가게';

COMMENT ON COLUMN ORDER_TBL.CODE IS '상태코드';

COMMENT ON TABLE ORDER_TBL IS '주문';

CREATE UNIQUE INDEX 엔터티1_PK10 ON ORDER_TBL
( ORDER_CODE );

ALTER TABLE ORDER_TBL
DROP PRIMARY KEY;

ALTER TABLE ORDER_TBL
 ADD CONSTRAINT 엔터티1_PK10 PRIMARY KEY ( ORDER_CODE )
 USING INDEX 엔터티1_PK10;

COMMENT ON COLUMN ORDER_TBL.MEM_CODE IS '회원코드';

COMMENT ON COLUMN ORDER_TBL.TOTAL_PRICE IS '구매금액';

COMMENT ON COLUMN ORDER_TBL.ORDER_CODE IS '주문코드';

COMMENT ON COLUMN ORDER_TBL.ORDER_TYPE IS '주문유형';

COMMENT ON COLUMN ORDER_TBL.TAKE_TIME IS '수령시간';

COMMENT ON COLUMN ORDER_TBL.ADDRESS IS '배송지';

COMMENT ON COLUMN ORDER_TBL.PHONE IS '연락처';

COMMENT ON COLUMN ORDER_TBL.STORE_NAME IS '주문가게';

COMMENT ON COLUMN ORDER_TBL.CODE IS '상태코드';

COMMENT ON TABLE ORDER_TBL IS '주문';


DROP TABLE POST_TBL;

CREATE TABLE POST_TBL
(
    POST_NO    NUMBER NOT NULL,
    BOARD_CODE    VARCHAR2(15) NOT NULL,
    POST_TITLE    VARCHAR2(100),
    MEM_CODE    NUMBER NOT NULL,
    POST_CONTENT    VARCHAR2(1500),
    POST_DATE    DATE,
    ANS_STATUS    VARCHAR2(10) DEFAULT 'N',
    QUE_NO    NUMBER,
    STATUS    VARCHAR2(3) DEFAULT 'N'
);

COMMENT ON COLUMN POST_TBL.POST_NO IS '게시글 번호';

COMMENT ON COLUMN POST_TBL.BOARD_CODE IS '게시판 코드';

COMMENT ON COLUMN POST_TBL.POST_TITLE IS '제목';

COMMENT ON COLUMN POST_TBL.MEM_CODE IS '작성자';

COMMENT ON COLUMN POST_TBL.POST_CONTENT IS '내용';

COMMENT ON COLUMN POST_TBL.POST_DATE IS '작성일';

COMMENT ON COLUMN POST_TBL.ANS_STATUS IS '답변여부';

COMMENT ON COLUMN POST_TBL.QUE_NO IS '질문 번호';

COMMENT ON COLUMN POST_TBL.STATUS IS '상태';

COMMENT ON TABLE POST_TBL IS '게시글';

CREATE UNIQUE INDEX 엔터티1_PK14 ON POST_TBL
( POST_NO );

ALTER TABLE POST_TBL
DROP PRIMARY KEY;

ALTER TABLE POST_TBL
 ADD CONSTRAINT 엔터티1_PK14 PRIMARY KEY ( POST_NO )
 USING INDEX 엔터티1_PK14;

COMMENT ON COLUMN POST_TBL.POST_NO IS '게시글 번호';

COMMENT ON COLUMN POST_TBL.BOARD_CODE IS '게시판 코드';

COMMENT ON COLUMN POST_TBL.POST_TITLE IS '제목';

COMMENT ON COLUMN POST_TBL.MEM_CODE IS '작성자';

COMMENT ON COLUMN POST_TBL.POST_CONTENT IS '내용';

COMMENT ON COLUMN POST_TBL.POST_DATE IS '작성일';

COMMENT ON COLUMN POST_TBL.ANS_STATUS IS '답변여부';

COMMENT ON COLUMN POST_TBL.QUE_NO IS '질문 번호';

COMMENT ON COLUMN POST_TBL.STATUS IS '상태';

COMMENT ON TABLE POST_TBL IS '게시글';


DROP TABLE PRODUCT_TBL;

CREATE TABLE PRODUCT_TBL
(
    SD_CODE    NUMBER NOT NULL,
    SD_NAME    VARCHAR2(30),
    M_DATE    DATE,
    PRICE    NUMBER,
    INGREDIENT    VARCHAR2(300),
    VOLUME    VARCHAR2(30),
    SD_IMG    VARCHAR2(200),
    CATEGORY    VARCHAR2(50),
    DISCOUNT_RATE    FLOAT DEFAULT 0,
    MEM_CODE    NUMBER NOT NULL,
    ORDERABLE_STATUS    VARCHAR2(10) DEFAULT 'Y',
    EXPIRY_DATE    NUMBER,
    TAG_NO    NUMBER NOT NULL,
    IS_DELETED    VARCHAR2(3) DEFAULT 'N'
);

COMMENT ON COLUMN PRODUCT_TBL.SD_CODE IS '반찬코드';

COMMENT ON COLUMN PRODUCT_TBL.SD_NAME IS '반찬명';

COMMENT ON COLUMN PRODUCT_TBL.M_DATE IS '제조일자';

COMMENT ON COLUMN PRODUCT_TBL.PRICE IS '가격';

COMMENT ON COLUMN PRODUCT_TBL.INGREDIENT IS '재료';

COMMENT ON COLUMN PRODUCT_TBL.VOLUME IS '용량';

COMMENT ON COLUMN PRODUCT_TBL.SD_IMG IS '반찬사진';

COMMENT ON COLUMN PRODUCT_TBL.CATEGORY IS '식품유형';

COMMENT ON COLUMN PRODUCT_TBL.DISCOUNT_RATE IS '할인율';

COMMENT ON COLUMN PRODUCT_TBL.MEM_CODE IS '사업자코드';

COMMENT ON COLUMN PRODUCT_TBL.ORDERABLE_STATUS IS '판매상태';

COMMENT ON COLUMN PRODUCT_TBL.EXPIRY_DATE IS '유통기한';

COMMENT ON COLUMN PRODUCT_TBL.TAG_NO IS '태그번호';

COMMENT ON COLUMN PRODUCT_TBL.IS_DELETED IS '삭제여부';

COMMENT ON TABLE PRODUCT_TBL IS '반찬';

CREATE UNIQUE INDEX 엔터티1_PK6 ON PRODUCT_TBL
( SD_CODE );

ALTER TABLE PRODUCT_TBL
DROP PRIMARY KEY;

ALTER TABLE PRODUCT_TBL
 ADD CONSTRAINT 엔터티1_PK6 PRIMARY KEY ( SD_CODE )
 USING INDEX 엔터티1_PK6;

COMMENT ON COLUMN PRODUCT_TBL.SD_CODE IS '반찬코드';

COMMENT ON COLUMN PRODUCT_TBL.SD_NAME IS '반찬명';

COMMENT ON COLUMN PRODUCT_TBL.M_DATE IS '제조일자';

COMMENT ON COLUMN PRODUCT_TBL.PRICE IS '가격';

COMMENT ON COLUMN PRODUCT_TBL.INGREDIENT IS '재료';

COMMENT ON COLUMN PRODUCT_TBL.VOLUME IS '용량';

COMMENT ON COLUMN PRODUCT_TBL.SD_IMG IS '반찬사진';

COMMENT ON COLUMN PRODUCT_TBL.CATEGORY IS '식품유형';

COMMENT ON COLUMN PRODUCT_TBL.DISCOUNT_RATE IS '할인율';

COMMENT ON COLUMN PRODUCT_TBL.MEM_CODE IS '사업자코드';

COMMENT ON COLUMN PRODUCT_TBL.ORDERABLE_STATUS IS '판매상태';

COMMENT ON COLUMN PRODUCT_TBL.EXPIRY_DATE IS '유통기한';

COMMENT ON COLUMN PRODUCT_TBL.TAG_NO IS '태그번호';

COMMENT ON COLUMN PRODUCT_TBL.IS_DELETED IS '삭제여부';

COMMENT ON TABLE PRODUCT_TBL IS '반찬';


DROP TABLE REPORT_TBL;

CREATE TABLE REPORT_TBL
(
    RV_CODE    NUMBER NOT NULL,
    REP_TYPE_CODE    NUMBER NOT NULL,
    REP_NO    NUMBER NOT NULL,
    REP_DATE    DATE,
    STATUS    VARCHAR2(10) DEFAULT 'N'
);

COMMENT ON COLUMN REPORT_TBL.RV_CODE IS '리뷰코드';

COMMENT ON COLUMN REPORT_TBL.REP_TYPE_CODE IS '유형번호';

COMMENT ON COLUMN REPORT_TBL.REP_NO IS '신고번호';

COMMENT ON COLUMN REPORT_TBL.REP_DATE IS '신고날짜';

COMMENT ON COLUMN REPORT_TBL.STATUS IS '처리상태';

COMMENT ON TABLE REPORT_TBL IS '신고내역';

CREATE UNIQUE INDEX 엔터티1_PK17 ON REPORT_TBL
( REP_NO );

ALTER TABLE REPORT_TBL
DROP PRIMARY KEY;

ALTER TABLE REPORT_TBL
 ADD CONSTRAINT 엔터티1_PK17 PRIMARY KEY ( REP_NO )
 USING INDEX 엔터티1_PK17;

COMMENT ON COLUMN REPORT_TBL.RV_CODE IS '리뷰코드';

COMMENT ON COLUMN REPORT_TBL.REP_TYPE_CODE IS '유형번호';

COMMENT ON COLUMN REPORT_TBL.REP_NO IS '신고번호';

COMMENT ON COLUMN REPORT_TBL.REP_DATE IS '신고날짜';

COMMENT ON COLUMN REPORT_TBL.STATUS IS '처리상태';

COMMENT ON TABLE REPORT_TBL IS '신고내역';


DROP TABLE REPORT_TYPE_TBL;

CREATE TABLE REPORT_TYPE_TBL
(
    REP_TYPE_CODE    NUMBER NOT NULL,
    REP_TYPE    VARCHAR2(100)
);

COMMENT ON COLUMN REPORT_TYPE_TBL.REP_TYPE_CODE IS '유형번호';

COMMENT ON COLUMN REPORT_TYPE_TBL.REP_TYPE IS '유형';

COMMENT ON TABLE REPORT_TYPE_TBL IS '신고유형';

CREATE UNIQUE INDEX 엔터티1_PK18 ON REPORT_TYPE_TBL
( REP_TYPE_CODE );

ALTER TABLE REPORT_TYPE_TBL
DROP PRIMARY KEY;

ALTER TABLE REPORT_TYPE_TBL
 ADD CONSTRAINT 엔터티1_PK18 PRIMARY KEY ( REP_TYPE_CODE )
 USING INDEX 엔터티1_PK18;

COMMENT ON COLUMN REPORT_TYPE_TBL.REP_TYPE_CODE IS '유형번호';

COMMENT ON COLUMN REPORT_TYPE_TBL.REP_TYPE IS '유형';

COMMENT ON TABLE REPORT_TYPE_TBL IS '신고유형';


DROP TABLE REVIEW_TBL;

CREATE TABLE REVIEW_TBL
(
    MEM_CODE    NUMBER NOT NULL,
    ORDER_CODE    NUMBER NOT NULL,
    RV_IMG    VARCHAR2(200),
    RV_CONTENT    VARCHAR2(450),
    RV_GRADE    FLOAT,
    RV_CODE    NUMBER NOT NULL
);

COMMENT ON COLUMN REVIEW_TBL.MEM_CODE IS '회원코드';

COMMENT ON COLUMN REVIEW_TBL.ORDER_CODE IS '주문코드';

COMMENT ON COLUMN REVIEW_TBL.RV_IMG IS '리뷰사진';

COMMENT ON COLUMN REVIEW_TBL.RV_CONTENT IS '리뷰내용';

COMMENT ON COLUMN REVIEW_TBL.RV_GRADE IS '평점';

COMMENT ON COLUMN REVIEW_TBL.RV_CODE IS '리뷰코드';

COMMENT ON TABLE REVIEW_TBL IS '리뷰';

CREATE UNIQUE INDEX 엔터티1_PK12 ON REVIEW_TBL
( RV_CODE );

ALTER TABLE REVIEW_TBL
DROP PRIMARY KEY;

ALTER TABLE REVIEW_TBL
 ADD CONSTRAINT 엔터티1_PK12 PRIMARY KEY ( RV_CODE )
 USING INDEX 엔터티1_PK12;

COMMENT ON COLUMN REVIEW_TBL.MEM_CODE IS '회원코드';

COMMENT ON COLUMN REVIEW_TBL.ORDER_CODE IS '주문코드';

COMMENT ON COLUMN REVIEW_TBL.RV_IMG IS '리뷰사진';

COMMENT ON COLUMN REVIEW_TBL.RV_CONTENT IS '리뷰내용';

COMMENT ON COLUMN REVIEW_TBL.RV_GRADE IS '평점';

COMMENT ON COLUMN REVIEW_TBL.RV_CODE IS '리뷰코드';

COMMENT ON TABLE REVIEW_TBL IS '리뷰';


DROP TABLE STORE_TBL;

CREATE TABLE STORE_TBL
(
    STORE_NAME    VARCHAR2(50),
    STORE_IMG    VARCHAR2(200),
    STORE_INFO    VARCHAR2(600),
    GRADE    FLOAT,
    DEL_COST    NUMBER,
    WORK_TIME    VARCHAR2(300),
    MEM_CODE    NUMBER NOT NULL
);

COMMENT ON COLUMN STORE_TBL.STORE_NAME IS '상호명';

COMMENT ON COLUMN STORE_TBL.STORE_IMG IS '상호이미지';

COMMENT ON COLUMN STORE_TBL.STORE_INFO IS '가게소개';

COMMENT ON COLUMN STORE_TBL.GRADE IS '평점';

COMMENT ON COLUMN STORE_TBL.DEL_COST IS '배송비';

COMMENT ON COLUMN STORE_TBL.WORK_TIME IS '영업시간';

COMMENT ON COLUMN STORE_TBL.MEM_CODE IS '사업자코드';

COMMENT ON TABLE STORE_TBL IS '가게정보';

CREATE UNIQUE INDEX 엔터티1_PK22 ON STORE_TBL
( MEM_CODE );

ALTER TABLE STORE_TBL
DROP PRIMARY KEY;

ALTER TABLE STORE_TBL
 ADD CONSTRAINT 엔터티1_PK22 PRIMARY KEY ( MEM_CODE )
 USING INDEX 엔터티1_PK22;

COMMENT ON COLUMN STORE_TBL.STORE_NAME IS '상호명';

COMMENT ON COLUMN STORE_TBL.STORE_IMG IS '상호이미지';

COMMENT ON COLUMN STORE_TBL.STORE_INFO IS '가게소개';

COMMENT ON COLUMN STORE_TBL.GRADE IS '평점';

COMMENT ON COLUMN STORE_TBL.DEL_COST IS '배송비';

COMMENT ON COLUMN STORE_TBL.WORK_TIME IS '영업시간';

COMMENT ON COLUMN STORE_TBL.MEM_CODE IS '사업자코드';

COMMENT ON TABLE STORE_TBL IS '가게정보';


DROP TABLE TAGS_TBL;

CREATE TABLE TAGS_TBL
(
    TAG_NO    NUMBER NOT NULL,
    TAG    VARCHAR2(30),
    STATUS    VARCHAR2(10) DEFAULT 'N'
);

COMMENT ON COLUMN TAGS_TBL.TAG_NO IS '태그번호';

COMMENT ON COLUMN TAGS_TBL.TAG IS '태그내용';

COMMENT ON COLUMN TAGS_TBL.STATUS IS '사용여부';

COMMENT ON TABLE TAGS_TBL IS '태그';

CREATE UNIQUE INDEX 엔터티1_PK20 ON TAGS_TBL
( TAG_NO );

ALTER TABLE TAGS_TBL
DROP PRIMARY KEY;

ALTER TABLE TAGS_TBL
 ADD CONSTRAINT 엔터티1_PK20 PRIMARY KEY ( TAG_NO )
 USING INDEX 엔터티1_PK20;

COMMENT ON COLUMN TAGS_TBL.TAG_NO IS '태그번호';

COMMENT ON COLUMN TAGS_TBL.TAG IS '태그내용';

COMMENT ON COLUMN TAGS_TBL.STATUS IS '사용여부';

COMMENT ON TABLE TAGS_TBL IS '태그';


DROP TABLE USER_TBL;

CREATE TABLE USER_TBL
(
    MEM_CODE    NUMBER NOT NULL,
    NAME    VARCHAR2(10),
    REP_COUNT    NUMBER
);

COMMENT ON COLUMN USER_TBL.MEM_CODE IS '회원코드';

COMMENT ON COLUMN USER_TBL.NAME IS '이름';

COMMENT ON COLUMN USER_TBL.REP_COUNT IS '신고횟수';

COMMENT ON TABLE USER_TBL IS '일반회원';

CREATE UNIQUE INDEX 엔터티1_PK8 ON USER_TBL
( MEM_CODE );

ALTER TABLE USER_TBL
DROP PRIMARY KEY;

ALTER TABLE USER_TBL
 ADD CONSTRAINT 엔터티1_PK8 PRIMARY KEY ( MEM_CODE )
 USING INDEX 엔터티1_PK8;

COMMENT ON COLUMN USER_TBL.MEM_CODE IS '회원코드';

COMMENT ON COLUMN USER_TBL.NAME IS '이름';

COMMENT ON COLUMN USER_TBL.REP_COUNT IS '신고횟수';

COMMENT ON TABLE USER_TBL IS '일반회원';
-- 외래키 싹다 추가해야함
ALTER TABLE USER_TBL ADD CONSTRAINT FK_MEM_CO8 FOREIGN KEY (MEM_CODE) REFERENCES MEMBER_TBL(MEM_CODE);

